services:
  - type: web
    name: music-frontend
    runtime: docker
    repo: https://github.com/timmmGZ/web
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: ./start_all_services.sh
